# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'EnablingTech'
    subscriptionId: 'c5ae1a85-c72f-4c38-bb05-b37ffc6246c7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rgSentinel'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/sstrauserThreatHunter/SentinelRepo/main/azuredeploy.json?token=GHSAT0AAAAAAB2WZXG264VZLKVCSK766R26Y3DDJDA'
    overrideParameters: '-projectName [EnterAProjectName]'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'